### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by mariusheine** [GEPROG/boydee#2]
It shall be possible for a user to login with its email and password.
On a successfull login the user shall be delegated to the Homescreen.
On a failed login the user shall remain on the login screen with its username still set and password shall be cleared.
An error message shall popup that user credentials were wrong.

When the email is not yet confirmed the user must confirm first before he can enter the application.

**Comment by anbraten** [comment]
Have a look at: https://github.com/perarnborg/vuex-oidc
